// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnbvjljwtjwoeimsgvby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuYnZqbGp3dGp3b2VpbXNndmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4ODcyOTIsImV4cCI6MjA3NzQ2MzI5Mn0.WL6K02XzNbpTZz-pLbfKeCcpQFffEooBqofguyLhA-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});